// ─── Demo seed data for first‑time visitors ────────────────────
// Mirrors the original `drive.tsx` mock content but as a real
// hierarchical tree stored in IndexedDB.

import type { DriveItem } from "./types";
import { genId } from "./utils";

const ME = "Admin";
const NOW = Date.now();
const HOUR = 1000 * 60 * 60;
const DAY = HOUR * 24;

export function buildSeed(): DriveItem[] {
  const fId = (n: string) => genId(`f_${n}`);
  const iId = (n: string) => genId(`i_${n}`);

  const financials = fId("fin");
  const contracts = fId("con");
  const marketing = fId("mkt");
  const hr = fId("hr");
  const engineering = fId("eng");
  const clients = fId("cli");

  return [
    // ── Folders (root) ──────────────────────────────────────
    {
      id: financials,
      parentId: null,
      name: "Financials",
      kind: "folder",
      size: 0,
      ownerId: "admin",
      ownerName: ME,
      createdAt: NOW - 30 * DAY,
      updatedAt: NOW - 2 * HOUR,
      starred: true,
      shared: false,
      trashedAt: null,
      tags: ["finance", "reports"],
      color: "green",
    },
    {
      id: contracts,
      parentId: null,
      name: "Contracts & Legal",
      kind: "folder",
      size: 0,
      ownerId: "admin",
      ownerName: ME,
      createdAt: NOW - 28 * DAY,
      updatedAt: NOW - 5 * HOUR,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["legal"],
      color: "rose",
    },
    {
      id: marketing,
      parentId: null,
      name: "Marketing Assets",
      kind: "folder",
      size: 0,
      ownerId: "admin",
      ownerName: ME,
      createdAt: NOW - 26 * DAY,
      updatedAt: NOW - 4 * DAY,
      starred: true,
      shared: true,
      trashedAt: null,
      tags: ["marketing"],
      color: "purple",
    },
    {
      id: hr,
      parentId: null,
      name: "HR Documents",
      kind: "folder",
      size: 0,
      ownerId: "admin",
      ownerName: ME,
      createdAt: NOW - 25 * DAY,
      updatedAt: NOW - 3 * DAY,
      starred: false,
      shared: false,
      trashedAt: null,
      tags: ["hr", "internal"],
      color: "violet",
    },
    {
      id: engineering,
      parentId: null,
      name: "Engineering Specs",
      kind: "folder",
      size: 0,
      ownerId: "admin",
      ownerName: ME,
      createdAt: NOW - 22 * DAY,
      updatedAt: NOW - 1 * DAY,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["engineering"],
      color: "cyan",
    },
    {
      id: clients,
      parentId: null,
      name: "Client Deliverables",
      kind: "folder",
      size: 0,
      ownerId: "admin",
      ownerName: ME,
      createdAt: NOW - 20 * DAY,
      updatedAt: NOW - 6 * HOUR,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["clients"],
      color: "amber",
    },

    // ── Files in Financials ────────────────────────────────
    {
      id: iId("q3rep"),
      parentId: financials,
      name: "Q3_Financial_Report.pdf",
      kind: "file",
      fileKind: "pdf",
      size: 2_516_582,
      ownerId: "admin",
      ownerName: "Alice W.",
      createdAt: NOW - 10 * DAY,
      updatedAt: NOW - 2 * HOUR,
      starred: true,
      shared: true,
      trashedAt: null,
      tags: ["report", "q3"],
      extension: "pdf",
      mimeType: "application/pdf",
    },
    {
      id: iId("invq3"),
      parentId: financials,
      name: "Inventory_Count_Q3.xlsx",
      kind: "file",
      fileKind: "spreadsheet",
      size: 876_544,
      ownerId: "admin",
      ownerName: "Dan T.",
      createdAt: NOW - 9 * DAY,
      updatedAt: NOW - 1 * DAY,
      starred: false,
      shared: false,
      trashedAt: null,
      tags: ["inventory"],
      extension: "xlsx",
    },
    {
      id: iId("budget"),
      parentId: financials,
      name: "Budget_2026_Draft.xlsx",
      kind: "file",
      fileKind: "spreadsheet",
      size: 421_000,
      ownerId: "admin",
      ownerName: "Alice W.",
      createdAt: NOW - 5 * DAY,
      updatedAt: NOW - 5 * HOUR,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["budget"],
      extension: "xlsx",
    },

    // ── Files in Contracts & Legal ────────────────────────
    {
      id: iId("contract"),
      parentId: contracts,
      name: "Contract_Draft_v3.docx",
      kind: "file",
      fileKind: "document",
      size: 1_258_291,
      ownerId: "admin",
      ownerName: "Carol L.",
      createdAt: NOW - 6 * DAY,
      updatedAt: NOW - 1 * DAY,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["draft"],
      extension: "docx",
    },
    {
      id: iId("nda"),
      parentId: contracts,
      name: "NDA_Strategic_Partner.pdf",
      kind: "file",
      fileKind: "pdf",
      size: 318_000,
      ownerId: "admin",
      ownerName: "Lisa C.",
      createdAt: NOW - 3 * DAY,
      updatedAt: NOW - 3 * DAY,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["nda"],
      extension: "pdf",
    },

    // ── Files in Marketing ────────────────────────────────
    {
      id: iId("banner"),
      parentId: marketing,
      name: "Marketing_Banner_FINAL.png",
      kind: "file",
      fileKind: "image",
      size: 3_879_000,
      ownerId: "admin",
      ownerName: "Marketing",
      createdAt: NOW - 8 * DAY,
      updatedAt: NOW - 4 * DAY,
      starred: true,
      shared: true,
      trashedAt: null,
      tags: ["banner", "campaign"],
      extension: "png",
    },
    {
      id: iId("logo"),
      parentId: marketing,
      name: "Logo_Mono.svg",
      kind: "file",
      fileKind: "image",
      size: 12_300,
      ownerId: "admin",
      ownerName: "Eve A.",
      createdAt: NOW - 14 * DAY,
      updatedAt: NOW - 14 * DAY,
      starred: true,
      shared: true,
      trashedAt: null,
      tags: ["brand"],
      extension: "svg",
    },

    // ── Files in HR ──────────────────────────────────────
    {
      id: iId("handbook"),
      parentId: hr,
      name: "Employee_Handbook_2026.pdf",
      kind: "file",
      fileKind: "pdf",
      size: 5_564_000,
      ownerId: "admin",
      ownerName: "HR Team",
      createdAt: NOW - 60 * DAY,
      updatedAt: NOW - 3 * DAY,
      starred: false,
      shared: false,
      trashedAt: null,
      tags: ["handbook"],
      extension: "pdf",
    },
    {
      id: iId("onboard"),
      parentId: hr,
      name: "Onboarding_Checklist.md",
      kind: "file",
      fileKind: "text",
      size: 4_200,
      ownerId: "admin",
      ownerName: "Carol L.",
      createdAt: NOW - 2 * DAY,
      updatedAt: NOW - 2 * DAY,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["onboarding"],
      extension: "md",
      content:
        "# New Hire Onboarding\n\n- [ ] IT equipment\n- [ ] Email & Slack accounts\n- [ ] HR documentation\n- [ ] 30/60/90 day plan\n- [ ] Training schedule\n",
    },

    // ── Files in Engineering ─────────────────────────────
    {
      id: iId("serverconf"),
      parentId: engineering,
      name: "Server_Config_Backup.conf",
      kind: "file",
      fileKind: "code",
      size: 45_000,
      ownerId: "admin",
      ownerName: "IT Team",
      createdAt: NOW - 12 * DAY,
      updatedAt: NOW - 5 * DAY,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["config", "ops"],
      extension: "conf",
    },
    {
      id: iId("apirenderings"),
      parentId: engineering,
      name: "Product_Renderings.zip",
      kind: "file",
      fileKind: "archive",
      size: 29_365_000,
      ownerId: "admin",
      ownerName: "Eve A.",
      createdAt: NOW - 7 * DAY,
      updatedAt: NOW - 2 * DAY,
      starred: false,
      shared: false,
      trashedAt: null,
      tags: ["assets"],
      extension: "zip",
    },

    // ── Files in Client Deliverables ────────────────────
    {
      id: iId("teamphoto"),
      parentId: clients,
      name: "Team_Photo_Offsite.jpg",
      kind: "file",
      fileKind: "image",
      size: 4_298_000,
      ownerId: "admin",
      ownerName: "Bob M.",
      createdAt: NOW - 4 * DAY,
      updatedAt: NOW - 5 * HOUR,
      starred: false,
      shared: true,
      trashedAt: null,
      tags: ["team", "photo"],
      extension: "jpg",
    },
    {
      id: iId("finalproposal"),
      parentId: clients,
      name: "Final_Proposal_TechNova.pdf",
      kind: "file",
      fileKind: "pdf",
      size: 2_134_000,
      ownerId: "admin",
      ownerName: "Sarah J.",
      createdAt: NOW - 1 * DAY,
      updatedAt: NOW - 1 * DAY,
      starred: true,
      shared: true,
      trashedAt: null,
      tags: ["proposal"],
      extension: "pdf",
    },

    // ── Loose file in root for variety ──────────────────
    {
      id: iId("readme"),
      parentId: null,
      name: "Welcome.md",
      kind: "file",
      fileKind: "text",
      size: 1_500,
      ownerId: "admin",
      ownerName: ME,
      createdAt: NOW - 1 * DAY,
      updatedAt: NOW - 1 * HOUR,
      starred: false,
      shared: false,
      trashedAt: null,
      tags: ["welcome"],
      extension: "md",
      content:
        "# Welcome to AnanDrive\n\nYour enterprise file manager.\n\n- Drag and drop to upload\n- Right-click any item for actions\n- Use the sidebar to jump between views\n- Press ⌘1 / ⌘2 to switch view modes\n",
    },
  ];
}

export function buildSeedActivity(): import("./types").ActivityEvent[] {
  // initial empty activity; events are generated as you use the app
  return [];
}
